language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libc6-dev

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test

after_success:
  - make gcov
  - bash <(curl -s https://codecov.io/bash)
