language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libc6-dev

script:
  - mkdir build && cd build
  - cmake .. -DENABLE_COVERAGE=On -DENABLE_TESTS=On -DCMAKE_BUILD_TYPE=ASAN && make && make test

after_success:
  - make gcov
  - bash <(curl -s https://codecov.io/bash)
